build:
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
  include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true     # disable publishing of .nupkg artifacts to

#---------------------------------#
#  Build Script                   #
#---------------------------------#
before_build:
  - ps: .\build.ps1 -Target "NuGet-Restore"
build_script:
  - ps: .\build.ps1 -Target Build

# Tests
test: on
test_script:
  - ps: .\build.ps1 -Target Test

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  # Whitelist
  only:
    - develop
    - master
    - /release/.*/
    - /hotfix/.*/

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
- Tools -> build.ps1
