build:
  publish_nuget: true

#---------------------------------#
#  Build Script                   #
#---------------------------------#
before_build:
  - ps: .\build.ps1 -Target "NuGet-Restore"
build_script:
  - ps: .\build.ps1 -Target Build

# Tests
test: on
test_script:
  - ps: .\build.ps1 -Target Test

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  # Whitelist
  only:
    - develop
    - master
    - /release/.*/
    - /hotfix/.*/

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
- Tools -> build.ps1


#---------------------------------#
#  Deploy                         #
#---------------------------------#
deploy:
  - provider: NuGet
    server: https://ci.appveyor.com/nuget/artemutin-3jj575ab2ab7
    api_key:
      secure: iqlq1qi66nascow18546o9d5
    artifact: TestLibCake.nupkg