#---------------------------------#
#  Build Script                   #
#---------------------------------#
before_build:
  - ps: .\build.ps1 -Target "NuGet-Restore"
build_script:
  - ps: .\build.ps1 -Target Build

# Tests
test: on
test_script:
  - ps: .\build.ps1 -Target Test

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  # Whitelist
  only:
    - develop
    - master
    - /release/.*/
    - /hotfix/.*/

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
- Tools -> build.ps1